#!/bin/bash

########## Banner ##########

banner="{
<BR><font color='#DAA520'>===========================================</BR></font>
<BR><font color='#008080'>******************Servicio Premium******************</BR></font>
<BR><font color='#DAA520'>===========================================</BR></font>
<BR><font color='#1E90FF'>------------------------Llamadas whatsapp ✔---------------------</BR></font>
<BR><font color='#1E90FF'>----------------------------Juegos Online ✔---------------------------</BR></font>
<BR><font color='#1E90FF'>--------------------------------Torrents 🚫--------------------------------</BR></font>
<BR><font color='#DAA520'>===========================================</BR></font>
<BR><font color='#860086'> -------------CONECTANDO AL MUNDO VIRTUAL-------------</BR></font>
<BR><font color='#DAA520'>===========================================</BR></font>
<BR><font color='#1E90FF'> Validando acceso.....</BR></font>
}
"
sed -i 's/DROPBEAR_BANNER=""/DROPBEAR_BANNER="/etc/issue.net"/g' /etc/default/dropbear
echo "$banner" > /etc/issue.net
service dropbear restart

banner2={
<BR><font color='#DAA520'>===============================================</BR></font>
<BR><font color='#008080'>********************Servicio Premium********************</BR></font>
<BR><font color='#DAA520'>===============================================</BR></font>
<BR><font color='#1E90FF'>---------------------------Llamadas whatsapp ✔-------------------------</BR></font>
<BR><font color='#1E90FF'>-------------------------------Juegos Online ✔------------------------------</BR></font>
<BR><font color='#1E90FF'>-----------------------------------Torrents 🚫------------------------------------</BR></font>
<BR><font color='#DAA520'>===============================================</BR></font>
<BR><font color='#860086'> ----------------CONECTANDO AL MUNDO VIRTUAL----------------</BR></font>
<BR><font color='#DAA520'>===============================================</BR></font>
<BR><font color='#1E90FF'> Validando acceso.....</BR></font>
}
"
echo "$banner2" > /etc/bannerssh
/etc/init.d/ssh restart
